Algoritmo "semnome"

Var
login , loginCorreto , senhaCorreta: caractere
senha : real

Inicio

loginCorreto <- "Stephany"
senhaCorreta <- "1010"

escreva ("digite seu login de acesso: ")
escreval (" ")

leia (login)
se (login = loginCorreto) entao

escreval ("login correto")
escreva ("senha")

leia (senha)
se (senha = senhaCorreta) entao
escreva ("acesso permitido")
senao
escreval ("acesso negado")
senao
escreval ("acesso negado")
fimse
fimse
Fimalgoritmo