Algoritmo "semnome"

Var
soma , valora , valorb , valorc: real

Inicio

  escreval ("digite um numero")
   leia (valora)
  escreval ("digite um numero")
   leia (valorb)
  escreval ("digite um numero")
   leia (valorc)

limpatela

soma <- valora + valorb

se (soma > valora) e (soma > valorb) entao
  escreval ( "a soma de valora e valorb é menor que: " , valorc)
senao
  escreval ( "a soma de valora e valorb é maior que: " , valorc)
fimse

Fimalgoritmo